version: '3.1'

services:

  db_tasks:
    container_name: db_tasks
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    image: postgres:15-alpine
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    command: 
      - 'postgres'
      - '-c'
      - 'port=${POSTGRES_PORT}'
    volumes:
      - db_tasks_vol:/var/lib/postgresql/data
    networks:
      - server_net
  tasks:
    container_name: tasks
    build: .
    depends_on:
      - db_tasks
    networks:
      - server_net
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_NAME: ${POSTGRES_NAME}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USE_SSL: ${POSTGRES_USE_SSL}

volumes:
  db_tasks_vol: {}

networks:
  server_net:
    driver: bridge